settings:
  title: 'Maximilian Gaedig Status Page'
  url: 'https://status.maximiliangaedig.com' # used for Slack messages
  logo: icon.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations
  ntfyPriority: 'urgent'

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: homepage
    name: Homepage
    description: 'My homepage'
    url: 'https://maximiliangaedig.com/'
    method: GET
    expectStatus: 200

  - id: matrix
    name: Matrix
    description: 'My matrix homeserver'
    url: 'https://maximiliangaedig.com/_matrix'
    method: GET
    expectStatus: 404
    linkable: false
  
  - id: mautrix-telegram
    name: Matrix Telegram
    description: 'Matrix to telegram bridge'
    url: 'https://maximiliangaedig.com/matrix/mautrix-telegram/login'
    method: GET
    expectStatus: 403
    linkable: false

  - id: mautrix-facebook
    name: Matrix Facebook
    description: 'Matrix to facebook messenger bridge'
    url: 'https://maximiliangaedig.com/matrix/mautrix-facebook/login'
    method: GET
    expectStatus: 403
    linkable: false

